import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row gap-1">
          <Link
            className="underline text-blue-500 visited:text-purple-500"
            href={"/"}
          >
            index
          </Link>
          <Link
            className="underline text-blue-500 visited:text-purple-500"
            href={"/users"}
          >
            users
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
